package app:evaluator;

// data types
interface types {
    record context {
        db: string,
    }
    record input {
        context: context,
    }

    record data {
        val: string,
    }
    record output {
        data: data,
    }
}

// executor functions exposed to evaluators
interface executor {
    // tracing
    trace: func(msg: string);
    debug: func(msg: string);
    warn: func(msg: string);
    error: func(msg: string);
}

// evaluator interface
interface evaluator {
    use types.{input, output};
    evaluate: func(input: input) -> result<output, string>;
}

world evaluator-world {
    import types;
    import executor;
    export evaluator;
}
