FROM rust:1.95-slim

# install dependencies required to build sqlx-cli
RUN apt-get update && apt-get install -y pkg-config libssl-dev

# install sqlx (Postgres only to speed up compilation)
RUN cargo install sqlx-cli --no-default-features --features rustls,postgres

WORKDIR /app

# set the default command to sqlx
ENTRYPOINT ["sqlx"]