//! Contracts used at the evaluator execution boundary.
//!
//! These types represent the canonical payload exchanged between a WASM evaluator and
//! the host runtime before persistence/aggregation mapping.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

/// Canonical response returned by a single evaluator invocation.
///
/// This is the transport/domain contract received from WASM evaluators.
/// The host converts it into normalized result rows used by storage and aggregation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct EvaluatorResponse {
    /// Stable machine identity for the evaluator that produced this payload.
    pub(crate) evaluator: EvaluatorIdentity,

    /// Findings emitted by this evaluator invocation.
    ///
    /// A single evaluator can emit multiple findings (for example, one per violation).
    #[serde(default)]
    pub(crate) results: Vec<EvaluatorFinding>,

    /// Optional evaluator-level metadata, diagnostics, timing, or trace context.
    ///
    /// This field is intentionally unstructured to allow evaluator-specific payloads.
    #[serde(default)]
    pub(crate) metadata: Value,
}

/// Canonical evaluator identity included in every evaluator response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct EvaluatorIdentity {
    /// Logical namespace for evaluator ownership/grouping.
    pub(crate) namespace: String,
    /// Evaluator package name within a namespace.
    pub(crate) name: String,
    /// Evaluator package version that produced the response.
    pub(crate) version: String,

    /// Optional content hash of the evaluator artifact (for strict reproducibility).
    pub(crate) content_hash: Option<String>,

    /// Optional declared contract version implemented by this evaluator.
    pub(crate) interface_version: Option<String>,
}

/// A single evaluator finding generated by one evaluator invocation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct EvaluatorFinding {
    /// Dimension this finding contributes to during aggregation.
    pub(crate) dimension: EvaluationDimension,

    /// Evaluator outcome before any run-level aggregation is applied.
    pub(crate) status: EvaluationStatus,

    /// Score expressed in evaluator-native format.
    pub(crate) score: Score,

    /// Indicates whether a failed/error finding should act as a hard gate.
    #[serde(default)]
    pub(crate) blocking: bool,

    /// Severity level associated with this finding.
    pub(crate) severity: Severity,

    /// Optional stable category identifier for summarization and dashboards.
    pub(crate) failure_category: Option<String>,

    /// Human-readable explanation intended for operators.
    pub(crate) reason: Option<String>,

    /// Structured evidence used for debugging, auditability, and drill-down reporting.
    #[serde(default)]
    pub(crate) evidence: Value,

    /// Optional labels for indexing/filtering/reporting use cases.
    #[serde(default)]
    pub(crate) tags: Vec<String>,
}

/// Dimension taxonomy used to group evaluator findings for aggregate scoring.
///
/// Serialized as a tagged variant (`{"kind": "quality"}` or
/// `{"kind": "other", "value": "custom-dimension"}`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(tag = "kind", content = "value", rename_all = "snake_case")]
pub(crate) enum EvaluationDimension {
    /// Factual and logical correctness of model output.
    Correctness,
    /// Structural/schema/format adherence.
    Format,
    /// Safety and policy compliance outcomes.
    Safety,
    /// Overall qualitative quality (style, usefulness, coherence).
    Quality,
    /// Performance-related metrics (latency, responsiveness).
    Latency,
    /// Correctness/quality of tool invocation behavior.
    ToolUse,
    /// Score calibration or confidence-alignment signals.
    Calibration,
    /// Domain-specific dimension not covered by built-in variants.
    Other(String),
}

/// Per-finding status produced directly by the evaluator.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(crate) enum EvaluationStatus {
    /// Check passed according to evaluator criteria.
    Passed,
    /// Check failed according to evaluator criteria.
    Failed,
    /// Evaluator failed to compute a valid judgment.
    Error,
    /// Check intentionally not evaluated for this invocation.
    Skipped,
}

/// Severity scale used to qualify impact when a finding is relevant.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(crate) enum Severity {
    /// No impact or not applicable.
    None,
    /// Minor impact.
    Low,
    /// Moderate impact.
    Medium,
    /// Major impact.
    High,
    /// Critical impact, often policy-blocking.
    Critical,
}

/// Outcome for pairwise/preference style evaluators.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(crate) enum PreferenceOutcome {
    /// Candidate is preferred over baseline/comparator.
    Preferred,
    /// No preference difference detected.
    Tie,
    /// Candidate is not preferred over baseline/comparator.
    NotPreferred,
}

/// Evaluator-native score.
///
/// Different evaluators can report scores in different forms. The host normalizes
/// each variant into `0.0..=1.0` when possible.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub(crate) enum Score {
    /// Pass/fail result.
    Binary { passed: bool },

    /// Numeric score with explicit scale.
    Range { value: f64, min: f64, max: f64 },

    /// Already normalized score.
    Normalized { value: f64 },

    /// Bucketed severity-like result.
    SeverityMapped { severity: Severity },

    /// Pairwise comparison.
    Preference { outcome: PreferenceOutcome },

    /// Informational finding that should not affect score.
    Informational,
}

/// Host-side normalized result used for aggregation/storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct NormalizedEvaluatorResult {
    /// Fully-qualified evaluator identity (`namespace:name@version`).
    pub(crate) evaluator_identifier: String,
    /// Aggregation dimension this row contributes to.
    pub(crate) dimension: EvaluationDimension,
    /// Evaluator status copied from the finding.
    pub(crate) status: EvaluationStatus,
    /// Stable discriminator for score representation.
    pub(crate) score_kind: String,

    /// Raw score value when the score type includes one.
    pub(crate) raw_score: Option<f64>,
    /// Raw score lower bound when defined by score type.
    pub(crate) raw_score_min: Option<f64>,
    /// Raw score upper bound when defined by score type.
    pub(crate) raw_score_max: Option<f64>,

    /// Always 0.0..=1.0 when present.
    pub(crate) normalized_score: Option<f64>,

    /// Whether this result should be treated as blocking by gate policy.
    pub(crate) blocking: bool,
    /// Severity copied from the source finding.
    pub(crate) severity: Severity,
    /// Optional stable failure category copied from the source finding.
    pub(crate) failure_category: Option<String>,
    /// Optional human-readable reason copied from the source finding.
    pub(crate) reason: Option<String>,
    /// Structured evidence copied from the source finding.
    pub(crate) evidence: Value,
    /// Reporting labels copied from the source finding.
    pub(crate) tags: Vec<String>,
}

impl Score {
    /// Converts evaluator-native score shapes into normalized `0.0..=1.0` values.
    ///
    /// Returns `None` when normalization is not meaningful (for example,
    /// informational scores or invalid range bounds).
    pub(crate) fn normalize(&self) -> Option<f64> {
        match self {
            Score::Binary { passed } => Some(if *passed { 1.0 } else { 0.0 }),
            Score::Range { value, min, max } => {
                if max <= min {
                    None
                } else {
                    Some(((value - min) / (max - min)).clamp(0.0, 1.0))
                }
            }
            Score::Normalized { value } => Some(value.clamp(0.0, 1.0)),
            Score::SeverityMapped { severity } => Some(match severity {
                Severity::None => 1.0,
                Severity::Low => 0.75,
                Severity::Medium => 0.5,
                Severity::High => 0.25,
                Severity::Critical => 0.0,
            }),
            Score::Preference { outcome } => Some(match outcome {
                PreferenceOutcome::Preferred => 1.0,
                PreferenceOutcome::Tie => 0.5,
                PreferenceOutcome::NotPreferred => 0.0,
            }),
            Score::Informational => None,
        }
    }

    /// Returns a stable snake_case discriminator for the score variant.
    pub(crate) fn kind(&self) -> &'static str {
        match self {
            Score::Binary { .. } => "binary",
            Score::Range { .. } => "range",
            Score::Normalized { .. } => "normalized",
            Score::SeverityMapped { .. } => "severity_mapped",
            Score::Preference { .. } => "preference",
            Score::Informational => "informational",
        }
    }

    /// Extracts raw score components in `(value, min, max)` form when available.
    ///
    /// The exact meaning depends on score variant. For non-numeric variants,
    /// components may be omitted.
    pub(crate) fn raw_parts(&self) -> (Option<f64>, Option<f64>, Option<f64>) {
        match self {
            Score::Binary { passed } => {
                let raw = if *passed { 1.0 } else { 0.0 };
                (Some(raw), Some(0.0), Some(1.0))
            }
            Score::Range { value, min, max } => (Some(*value), Some(*min), Some(*max)),
            Score::Normalized { value } => (Some(*value), Some(0.0), Some(1.0)),
            Score::SeverityMapped { .. } => (None, None, None),
            Score::Preference { outcome } => {
                let raw = match outcome {
                    PreferenceOutcome::Preferred => 1.0,
                    PreferenceOutcome::Tie => 0.5,
                    PreferenceOutcome::NotPreferred => 0.0,
                };
                (Some(raw), Some(0.0), Some(1.0))
            }
            Score::Informational => (None, None, None),
        }
    }
}

impl EvaluatorResponse {
    /// Normalizes all findings in this response into host aggregation rows.
    ///
    /// The resulting rows preserve source status/severity/evidence while adding
    /// normalized score fields and a fully-qualified evaluator identifier.
    pub(crate) fn normalize(self) -> Vec<NormalizedEvaluatorResult> {
        let evaluator_identifier = format!(
            "{}:{}@{}",
            self.evaluator.namespace, self.evaluator.name, self.evaluator.version
        );

        self.results
            .into_iter()
            .map(|finding| {
                let (raw_score, raw_score_min, raw_score_max) = finding.score.raw_parts();

                NormalizedEvaluatorResult {
                    evaluator_identifier: evaluator_identifier.clone(),
                    dimension: finding.dimension,
                    status: finding.status,
                    score_kind: finding.score.kind().to_string(),
                    raw_score,
                    raw_score_min,
                    raw_score_max,
                    normalized_score: finding.score.normalize(),
                    blocking: finding.blocking,
                    severity: finding.severity,
                    failure_category: finding.failure_category,
                    reason: finding.reason,
                    evidence: finding.evidence,
                    tags: finding.tags,
                }
            })
            .collect()
    }
}

/// Aggregation-ready grouping helper.
///
/// Groups normalized results by dimension while preserving insertion order of
/// results within each dimension bucket.
pub(crate) fn group_by_dimension(
    results: &[NormalizedEvaluatorResult],
) -> BTreeMap<EvaluationDimension, Vec<&NormalizedEvaluatorResult>> {
    let mut grouped = BTreeMap::new();

    for result in results {
        grouped
            .entry(result.dimension.clone())
            .or_insert_with(Vec::new)
            .push(result);
    }

    grouped
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_range_returns_none_for_invalid_bounds() {
        let score = Score::Range {
            value: 1.0,
            min: 10.0,
            max: 5.0,
        };

        assert_eq!(score.normalize(), None);
    }

    #[test]
    fn response_normalize_uses_identifier_format() {
        let response = EvaluatorResponse {
            evaluator: EvaluatorIdentity {
                namespace: "vigilo".to_string(),
                name: "sentiment".to_string(),
                version: "0.1.0".to_string(),
                content_hash: None,
                interface_version: None,
            },
            results: vec![EvaluatorFinding {
                dimension: EvaluationDimension::Quality,
                status: EvaluationStatus::Passed,
                score: Score::Normalized { value: 0.8 },
                blocking: false,
                severity: Severity::None,
                failure_category: None,
                reason: None,
                evidence: Value::Null,
                tags: vec![],
            }],
            metadata: Value::Null,
        };

        let normalized = response.normalize();
        assert_eq!(normalized.len(), 1);
        assert_eq!(normalized[0].evaluator_identifier, "vigilo:sentiment@0.1.0");
        assert_eq!(normalized[0].normalized_score, Some(0.8));
    }
}
